import { Paths } from "@/lib/pageroutes"

export const Documents: Paths[] = [
  {
    title: "JavaScript",
    href: "/javascript",
    items: [
      {
        title: "Basic JavaScript",
        href: "/basic",
        noLink: true,
        items: [
          { title: "JS Tutorial", href: "/tutorial" },
          { title: "JS Introduction", href: "/introduction" },
          { title: "JS Where To", href: "/where-to" },
          { title: "JS Output", href: "/output" },
          { title: "JS Syntax", href: "/syntax" },
          { title: "JS Variables", href: "/variables" },
          { title: "JS Operators", href: "/operators" },
          { title: "JS If Conditions", href: "/if-conditions" },
          { title: "JS Loops", href: "/loops" },
          { title: "JS Strings", href: "/strings" },
          { title: "JS String Methods", href: "/string-methods" },
          { title: "JS Numbers", href: "/numbers" },
          { title: "JS Functions", href: "/functions" },
          { title: "JS Objects", href: "/objects" },
          { title: "JS Dates", href: "/dates" },
          { title: "JS Arrays", href: "/arrays" },
          { title: "JS Typed Arrays", href: "/typed-arrays" },
          { title: "JS Sets", href: "/sets" },
          { title: "JS Maps", href: "/maps" },
          { title: "JS Math", href: "/math" },
          { title: "JS RegExp", href: "/regexp" },
          { title: "JS Data Types", href: "/data-types" },
          { title: "JS Errors", href: "/errors" },
          { title: "JS Events", href: "/events" },
          { title: "JS Programming", href: "/programming" },
          { title: "JS References", href: "/references" },
          { title: "JS Versions", href: "/versions" },
        ],
      },
      {
        title: "JS Advanced",
        href: "/advanced",
        noLink: true,
        items: [
          { title: "Functions", href: "/functions" },
          { title: "Objects", href: "/objects" },
          { title: "Classes", href: "/classes" },
          { title: "Iterations", href: "/iterations" },
          { title: "Asynchronous", href: "/asynchronous" },
          { title: "Modules", href: "/modules" },
          { title: "Meta & Proxy", href: "/meta-proxy" },
          { title: "HTML DOM", href: "/html-dom" },
          { title: "Windows", href: "/windows" },
          { title: "Web API", href: "/web-api" },
          { title: "AJAX", href: "/ajax" },
          { title: "JSON", href: "/json" },
          { title: "jQuery", href: "/jquery" },
          { title: "Graphics", href: "/graphics" },
          { title: "Examples", href: "/examples" },
          { title: "Reference", href: "/reference" },
        ],
      },
    ],
  },
  {
    title: "React",
    href: "/react",
    items: [],
  },
  {
    title: "Tailwind CSS",
    href: "/tailwind",
    items: [],
  },
  {
    title: "Next.js",
    href: "/nextjs",
    items: [],
  },
]
