import { Paths } from "@/lib/pageroutes"

export const Documents: Paths[] = [
  {
    title: "JavaScript",
    href: "/javascript",
    items: [
      {
        title: "Basic JavaScript",
        href: "/basic",
        noLink: true,
        items: [
          { title: "Tutorial", href: "/tutorial" },
          { title: "Introduction", href: "/introduction" },
          { title: "Where To", href: "/where-to" },
          { title: "Output", href: "/output" },
          { title: "Syntax", href: "/syntax" },
          { title: "Variables", href: "/variables" },
          { title: "Operators", href: "/operators" },
          { title: "If Conditions", href: "/if-conditions" },
          { title: "Loops", href: "/loops" },
          { title: "Strings", href: "/strings" },
          { title: "String Methods", href: "/string-methods" },
          { title: "Numbers", href: "/numbers" },
          { title: "Functions", href: "/functions" },
          { title: "Objects", href: "/objects" },
          { title: "Dates", href: "/dates" },
          { title: "Arrays", href: "/arrays" },
          { title: "Typed Arrays", href: "/typed-arrays" },
          { title: "Sets", href: "/sets" },
          { title: "Maps", href: "/maps" },
          { title: "Math", href: "/math" },
          { title: "RegExp", href: "/regexp" },
          { title: "Data Types", href: "/data-types" },
          { title: "Errors", href: "/errors" },
          { title: "Events", href: "/events" },
          { title: "Programming", href: "/programming" },
          { title: "References", href: "/references" },
          { title: "Versions", href: "/versions" },
        ],
      },
      {
        title: "JS Advanced",
        href: "/advanced",
        noLink: true,
        items: [
          { title: "Functions", href: "/functions" },
          { title: "Objects", href: "/objects" },
          { title: "Classes", href: "/classes" },
          { title: "Iterations", href: "/iterations" },
          { title: "Asynchronous", href: "/asynchronous" },
          { title: "Modules", href: "/modules" },
          { title: "Meta & Proxy", href: "/meta-proxy" },
          { title: "HTML DOM", href: "/html-dom" },
          { title: "Windows", href: "/windows" },
          { title: "Web API", href: "/web-api" },
          { title: "AJAX", href: "/ajax" },
          { title: "JSON", href: "/json" },
          { title: "jQuery", href: "/jquery" },
          { title: "Graphics", href: "/graphics" },
          { title: "Examples", href: "/examples" },
          { title: "Reference", href: "/reference" },
        ],
      },
    ],
  },
  {
    title: "React",
    href: "/react",
    items: [],
  },
  {
    title: "Tailwind CSS",
    href: "/tailwind",
    items: [],
  },
  {
    title: "Next.js",
    href: "/nextjs",
    items: [],
  },
]
